baseURL = 'https://salmacis214.github.io/'
locale = 'en-gb'
title = 'Tarun Nair'
theme = 'mytheme'

[taxonomies]
  category = 'categories'
  tag = 'tags'

[caches]
  [caches.images]
    dir = ':cacheDir/images'